/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PrivacyNotice = {
  _id: string;
  _type: "privacyNotice";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lastReviewed: string;
  intro: string;
  sections: Array<{
    heading: string;
    paragraphs: Array<string>;
    _key: string;
  }>;
};

export type Artwork = {
  _id: string;
  _type: "artwork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  artist: string;
  game: string;
  image: ImageWithAlt;
  sourceUrl: string;
  displayOrder: number;
  enabled: boolean;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type FacebookFeature = {
  _id: string;
  _type: "facebookFeature";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  postUrl: string;
  excerpt: string;
  image: ImageWithAlt;
  displayOrder: number;
  enabled: boolean;
};

export type Rule = {
  _id: string;
  _type: "rule";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedString;
  body: {
    en: RulesBlockContent;
    si: RulesBlockContent;
  };
  displayOrder: number;
  anchorId: Slug;
  enabled: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type RulesBlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type LocalizedString = {
  _type: "localizedString";
  en: string;
  si: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  shortName: string;
  heroEyebrow?: string;
  heroHeading: string;
  heroBody: string;
  heroImage?: ImageWithAlt;
  memberCount: number;
  memberCountLabel: string;
  memberCountSource: string;
  aboutHeading: string;
  aboutBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  aboutFacts: Array<{
    key: string;
    title: string;
    description: string;
    _key: string;
  }>;
  socialLinks: Array<{
    platform: "facebook" | "discord" | "steam" | "reddit" | "instagram" | "youtube";
    label: string;
    url: string;
    enabled: boolean;
    order: number;
    _key: string;
  }>;
  featuredAnnouncement?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "announcement";
  };
  rulesHeadingEn: string;
  rulesHeadingSi: string;
  rulesIntroEn: string;
  rulesIntroSi: string;
  rulesOutroTitleEn: string;
  rulesOutroTitleSi: string;
  rulesOutroBodyEn: string;
  rulesOutroBodySi: string;
  rulesLastUpdated: string;
  seoTitle: string;
  seoDescription: string;
  defaultOgImage: ImageWithAlt;
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  kind: "ANNOUNCEMENT" | "RULES UPDATE" | "COMMUNITY" | "EVENT";
  excerpt: string;
  body: AnnouncementBlockContent;
  publishedAt: string;
  coverImage?: ImageWithAlt;
  seoDescription?: string;
};

export type AnnouncementBlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & ImageWithAlt>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type LocalizedText = {
  _type: "localizedText";
  en: string;
  si: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = PrivacyNotice | Artwork | ImageWithAlt | FacebookFeature | Rule | Slug | RulesBlockContent | LocalizedString | SiteSettings | Announcement | AnnouncementBlockContent | SanityImageCrop | SanityImageHotspot | LocalizedText | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && !(_id in path("drafts.**"))][0]{  siteName, shortName, heroEyebrow, heroHeading, heroBody, heroImage,  memberCount, memberCountLabel, memberCountSource, aboutHeading, aboutBody,  aboutFacts[]{ key, title, description },  "socialLinks": socialLinks[enabled == true] | order(order asc){ platform, label, url, enabled },  rulesHeadingEn, rulesHeadingSi, rulesIntroEn, rulesIntroSi,  rulesOutroTitleEn, rulesOutroTitleSi, rulesOutroBodyEn, rulesOutroBodySi,  rulesLastUpdated,  seoTitle, seoDescription, defaultOgImage}
export type SITE_SETTINGS_QUERYResult = {
  siteName: string;
  shortName: string;
  heroEyebrow: string | null;
  heroHeading: string;
  heroBody: string;
  heroImage: ImageWithAlt | null;
  memberCount: number;
  memberCountLabel: string;
  memberCountSource: string;
  aboutHeading: string;
  aboutBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  aboutFacts: Array<{
    key: string;
    title: string;
    description: string;
  }>;
  socialLinks: Array<{
    platform: "discord" | "facebook" | "instagram" | "reddit" | "steam" | "youtube";
    label: string;
    url: string;
    enabled: true;
  }>;
  rulesHeadingEn: string;
  rulesHeadingSi: string;
  rulesIntroEn: string;
  rulesIntroSi: string;
  rulesOutroTitleEn: string;
  rulesOutroTitleSi: string;
  rulesOutroBodyEn: string;
  rulesOutroBodySi: string;
  rulesLastUpdated: string;
  seoTitle: string;
  seoDescription: string;
  defaultOgImage: ImageWithAlt;
} | null;
// Variable: RULES_QUERY
// Query: *[_type == "rule" && enabled == true && !(_id in path("drafts.**"))]  | order(displayOrder asc, _createdAt asc){    _id, displayOrder, title, body  }
export type RULES_QUERYResult = Array<{
  _id: string;
  displayOrder: number;
  title: LocalizedString;
  body: {
    en: RulesBlockContent;
    si: RulesBlockContent;
  };
}>;
// Variable: ANNOUNCEMENT_PROJECTION
// Query: {  _id, title, "slug": slug.current, kind, excerpt, body, coverImage, publishedAt}
export type ANNOUNCEMENT_PROJECTIONResult = {
  _id: never;
  title: never;
  slug: never;
  kind: never;
  excerpt: never;
  body: never;
  coverImage: never;
  publishedAt: never;
};
// Variable: ANNOUNCEMENTS_QUERY
// Query: *[  _type == "announcement" &&  !(_id in path("drafts.**")) &&  defined(publishedAt) &&  publishedAt <= now()] | order(publishedAt desc) {  _id, title, "slug": slug.current, kind, excerpt, body, coverImage, publishedAt}
export type ANNOUNCEMENTS_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  kind: "ANNOUNCEMENT" | "COMMUNITY" | "EVENT" | "RULES UPDATE";
  excerpt: string;
  body: AnnouncementBlockContent;
  coverImage: ImageWithAlt | null;
  publishedAt: string;
}>;
// Variable: ANNOUNCEMENT_BY_SLUG_QUERY
// Query: *[  _type == "announcement" &&  !(_id in path("drafts.**")) &&  defined(publishedAt) &&  publishedAt <= now() &&  slug.current == $slug][0] {  _id, title, "slug": slug.current, kind, excerpt, body, coverImage, publishedAt}
export type ANNOUNCEMENT_BY_SLUG_QUERYResult = {
  _id: string;
  title: string;
  slug: string;
  kind: "ANNOUNCEMENT" | "COMMUNITY" | "EVENT" | "RULES UPDATE";
  excerpt: string;
  body: AnnouncementBlockContent;
  coverImage: ImageWithAlt | null;
  publishedAt: string;
} | null;
// Variable: FEATURED_ANNOUNCEMENT_QUERY
// Query: coalesce(  *[    _type == "announcement" &&    !(_id in path("drafts.**")) &&    defined(publishedAt) &&    publishedAt <= now() &&    _id == *[_type == "siteSettings" && !(_id in path("drafts.**"))][0].featuredAnnouncement._ref  ][0] {  _id, title, "slug": slug.current, kind, excerpt, body, coverImage, publishedAt},  *[    _type == "announcement" &&    !(_id in path("drafts.**")) &&    defined(publishedAt) &&    publishedAt <= now()  ] | order(publishedAt desc)[0] {  _id, title, "slug": slug.current, kind, excerpt, body, coverImage, publishedAt})
export type FEATURED_ANNOUNCEMENT_QUERYResult = {
  _id: string;
  title: string;
  slug: string;
  kind: "ANNOUNCEMENT" | "COMMUNITY" | "EVENT" | "RULES UPDATE";
  excerpt: string;
  body: AnnouncementBlockContent;
  coverImage: ImageWithAlt | null;
  publishedAt: string;
} | null;
// Variable: FACEBOOK_FEATURES_QUERY
// Query: *[  _type == "facebookFeature" &&  enabled == true &&  !(_id in path("drafts.**"))] | order(displayOrder asc)[0...3]{  _id, title, excerpt, postUrl, image, displayOrder}
export type FACEBOOK_FEATURES_QUERYResult = Array<{
  _id: string;
  title: string;
  excerpt: string;
  postUrl: string;
  image: ImageWithAlt;
  displayOrder: number;
}>;
// Variable: ARTWORK_QUERY
// Query: *[  _type == "artwork" &&  enabled == true &&  !(_id in path("drafts.**"))] | order(displayOrder asc, _createdAt asc){  _id, title, artist, game, image, sourceUrl, displayOrder}
export type ARTWORK_QUERYResult = Array<{
  _id: string;
  title: string;
  artist: string;
  game: string;
  image: ImageWithAlt;
  sourceUrl: string;
  displayOrder: number;
}>;
// Variable: PRIVACY_QUERY
// Query: *[_type == "privacyNotice" && !(_id in path("drafts.**"))][0]{  lastReviewed, intro, sections}
export type PRIVACY_QUERYResult = {
  lastReviewed: string;
  intro: string;
  sections: Array<{
    heading: string;
    paragraphs: Array<string>;
    _key: string;
  }>;
} | null;

